#!/usr/bin/env python3
"""Regenerate test/mvs/tstcnvkat.h, the known answers for the #190
float <-> long long helpers (test/host/tstcnvdi.c, test/mvs/tstcnvdi.c).

Python's integers and Fractions are exact, so every expected value here is
computed without any floating-point hardware and independently of the
helpers under test.  The rules are the ones @@fixdi.c and @@fltdi.c state:

  HFP -> integer   truncate toward zero, then modulo 2^64 (a negative value
                   is its two's complement), so signed and unsigned agree
  integer -> HFP   14 hex digits for a double, 6 for a float; more digits
                   are rounded by adding half of the last kept digit to the
                   magnitude and truncating, which is how LRER rounds

    python3 test/mvs/tstcnvkat.py > test/mvs/tstcnvkat.h
"""
import random
from fractions import Fraction

M64 = (1 << 64) - 1


def hfp_value(hi, lo, short):
    """exact value of an HFP bit pattern (short: lo is ignored)"""
    frac = (hi & 0x00FFFFFF) if short else ((hi & 0x00FFFFFF) << 32) | lo
    digits = 6 if short else 14
    e = (hi >> 24) & 0x7F
    v = Fraction(frac, 16 ** digits) * Fraction(16) ** (e - 64)
    return -v if hi & 0x80000000 else v


def fix(hi, lo, short):
    v = hfp_value(hi, lo, short)
    t = abs(v.numerator) // v.denominator          # truncate toward zero
    if v < 0:
        t = -t
    return t & M64


def to_hfp(x, digits):
    """HFP bits (hi, lo) of the integer x rounded to DIGITS hex digits"""
    if x == 0:
        return 0, 0
    sign = 0x80000000 if x < 0 else 0
    m = abs(x)
    n = len('%x' % m)
    if n <= digits:
        f = m * 16 ** (digits - n)
    else:
        unit = 16 ** (n - digits)
        f = (m + unit // 2) // unit
        if f >= 16 ** digits:                     # the round carried
            f //= 16
            n += 1
    e = 64 + n
    if digits == 14:
        return sign | (e << 24) | (f >> 32), f & 0xFFFFFFFF
    return sign | (e << 24) | f, 0


def s64(v):
    return v - (1 << 64) if v >> 63 else v


def words(v):
    return "0x%08X,0x%08X" % (v >> 32, v & 0xFFFFFFFF)


rnd = random.Random(190)

# --- integer -> HFP operands -------------------------------------------------
ints = [0, 1, -1, 15, 16, 255, -256, 0xFFFFFF, 0x1000000, 0x1000001,
        (1 << 24) + 8, (1 << 24) + 7, 2147483647, -2147483648, 305419896,
        1 << 32, (1 << 53) + 1, (1 << 56) - 1, 1 << 56, (1 << 56) + 7,
        (1 << 56) + 8, (1 << 56) + 9, 0x0FFFFFFFFFFFFFF8, 0x0FFFFFFFFFFFFFF7,
        (1 << 63) - 1, -(1 << 63), -((1 << 63) - 1), 123456789012345678,
        -123456789012345678, 0x7FFFFF80, 0x7FFFFF7F]
for _ in range(60):
    w = rnd.randrange(1, 64)
    v = rnd.getrandbits(w)
    ints.append(-v if rnd.random() < 0.4 else v)

# --- HFP -> integer operands ---------------------------------------------------
hfps = [
    (0x00000000, 0x00000000), (0x41100000, 0x00000000), (0x41180000, 0x00000000),
    (0xC1180000, 0x00000000), (0xC0800000, 0x00000000), (0xC1280000, 0x00000000),
    (0x487FFFFF, 0xFF000000), (0x48800000, 0x00000000), (0x49100000, 0x00100000),
    (0x49100000, 0x00000000), (0xC8800000, 0x00000000), (0x508AC723, 0x0489E800),
    (0xD08AC723, 0x0489E800), (0x40FFFFFF, 0xFFFFFFF9), (0x4775BCD1, 0x5C000000),
    (0xC775BCD1, 0x5C000000), (0x50800000, 0x00000000), (0xD0800000, 0x00000000),
    (0x51100000, 0x00000000), (0x51FFFFFF, 0xFFFFFFFF), (0x7FFFFFFF, 0xFFFFFFFF),
    (0xFFFFFFFF, 0xFFFFFFFF), (0x4E00FFFF, 0xFFFFFFFF), (0x4F00000F, 0x00000000),
    (0x00FFFFFF, 0xFFFFFFFF), (0x3F800000, 0x00000000), (0x4E000000, 0x00000001),
    (0xCE000000, 0x00000001), (0x4F080000, 0x00000000), (0x42000100, 0x00000000),
]
for _ in range(60):
    e = rnd.choice([rnd.randrange(0x38, 0x56), rnd.randrange(0, 128)])
    hi = (rnd.getrandbits(1) << 31) | (e << 24) | rnd.getrandbits(24)
    hfps.append((hi, rnd.getrandbits(32)))

print("/* tstcnvkat.h - generated by test/mvs/tstcnvkat.py for #190; do not edit.")
print(" * Expected values are exact (Python Fractions), independent of the helpers. */")
print()
print("/* integer x (hi,lo); then its double (hi,lo) and its float bits */")
print("static const unsigned kat_flt[][5] = {")
for x in ints:
    dh, dl = to_hfp(x, 14)
    fh, _ = to_hfp(x, 6)
    print("    { %s, 0x%08X,0x%08X, 0x%08X }," % (words(x & M64), dh, dl, fh))
print("};")
print()
print("/* long HFP (hi,lo); its integer part as long long (hi,lo); then the same")
print("   for the short HFP whose bits are hi alone */")
print("static const unsigned kat_fix[][6] = {")
for hi, lo in hfps:
    print("    { 0x%08X,0x%08X, %s, %s }," % (hi, lo, words(fix(hi, lo, False)),
                                           words(fix(hi, 0, True))))
print("};")
