#import "../bookmaster/bookmaster.typ": *

= Migrating from crent370 and libc370 1.x <pg-migrate>

#idx("migration", "from libc370 1.x")#idx("crent370")
libc370 2.0 reorganized the public headers. The functions, their behavior
and the code a program links are, with a short list of exceptions, what
1.x had -- but almost every source that includes a library header has to
change its #cmd("#include") lines. This appendix says what changed, how to
stay on 1.x until you are ready, and how to migrate one source file at a
time.

2.0 is a hard cut: there are no compatibility headers and no deprecated
names. An include of 1.x either resolves to its 2.0 header or does not
compile.

== Coming from crent370 <pg-migrate-crent>

crent370 is the name under which the library was created, before it became
the library of the cc370 toolchain and was renamed libc370. A program built
against crent370 uses the header names of libc370 1.x and migrates as a 1.x
program, as described in the rest of this appendix. In addition:

- The library is no longer a dependency of the project. It is installed in
  the sysroot of cc370, which finds its headers without #cmd("-I") and
  links #cmd("libc.a") with #cmd("-lc") (@pg-intro-install). Remove a
  dependency on crent370 from the build.
- libc370 2.1 and later need cc370 1.1.0 or later\; every header stops
  with #cmd("#error") under an older compiler.
- Assembler source that copies #cmd("PDPMAIN") was generated by a
  compiler before cc370. The macros #cmd("PDPMAIN"), #cmd("PDP370"),
  #cmd("PDP380"), #cmd("PDP390") and #cmd("PDPORIG") are not shipped any
  more: compile the C source again with cc370.

== Staying on 1.x <pg-migrate-stay>

The last 1.x release is 1.0.8. Its tag #cmd("v1.0.8") and the branch
#cmd("1.x") remain in the libc370 repository.

- In an mbt project, declare #cmd("libc370 = \"1.0.8\"") in the
  #cmd("[toolchain]") table of #cmd("project.toml").
- Installed by hand: #cmd("git checkout v1.0.8") and #cmd("make install").

#cmd("make install") installs into the sysroot of the first cc370 on the
#cmd("PATH") and _replaces_ the headers there. To keep both, install the
toolchain twice under two prefixes, each with its own libc370, and build each
project with the #cmd("PATH") it needs. mbt refuses a sysroot older than the
#cmd("[toolchain]") pin of a project, so a wrong one is noticed.

== What Changed in 2.0 <pg-migrate-changes>

- *The headers moved into a tree:* #cmd("mvs/") for the MVS run time and
  services, #cmd("ext/") for portable extras (dynamic arrays, 64-bit
  helpers, time beyond 2038), #cmd("ibm/") for IBM control blocks, data
  layout only, #cmd("s370/") for the architecture, and the POSIX headers
  #cmd("<sys/socket.h>"), #cmd("<netinet/in.h>"), #cmd("<arpa/inet.h>"),
  #cmd("<strings.h>"), #cmd("<unistd.h>") and others. Headers that mixed
  purposes were _split_\; internal ones left the sysroot.
- *Names:* 880 of the 5481 public names of 1.x are gone from the public
  headers, nearly all of them declared and never built, or internal. The
  few a program can have used have a replacement (@pg-migrate-removed).
- *Cryptography* -- SHA-256, Blowfish and base64 -- moved to the separate
  library crypto370. In an mbt project, add
  #cmd("\"mvslovers/crypto370\" = \">=1.0.0\"") to #cmd("[dependencies]").
  #cmd("<clibb64.h>") is #cmd("<base64.h>") there\; the C names did not
  change, the external names did (#cmd("B64ENC"), #cmd("B64DEC")).
- *A few interfaces changed their meaning* (@pg-migrate-meaning).
- The library itself is compiled as C99 (#cmd("-std=gnu99")).

== The Headers You Most Likely Include <pg-migrate-headers>

@pg-migrate-headers-tab lists the 1.x headers that programs include most,
and where they went. The complete map of all 153 headers is the file
#cmd("sdk/headermap.tsv") in the libc370 source repository.

#tab(caption: [Where the common 1.x headers went])[
  #table(columns: (1.5in, 1fr), align: left,
    [*1.x*], [*2.0*],
    [#cmd("clibwto.h")], [#cmd("mvs/wto.h")],
    [#cmd("clibos.h")], [split: #cmd("mvs/pds.h"), #cmd("s370/atomic.h"),
      #cmd("mvs/xmem.h"), #cmd("mvs/apf.h"), #cmd("mvs/link.h"),
      #cmd("mvs/storage.h"), #cmd("mvs/thread.h")],
    [#cmd("clibary.h")], [#cmd("ext/array.h")],
    [#cmd("clibcrt.h"), #cmd("clibgrt.h"), #cmd("clibppa.h")],
      [#cmd("mvs/crt.h")],
    [#cmd("clibecb.h")], [#cmd("mvs/ecb.h")],
    [#cmd("clibtry.h"), #cmd("clibstae.h")], [#cmd("mvs/recovery.h")],
    [#cmd("racf.h")], [#cmd("mvs/racf.h")],
    [#cmd("time64.h")], [#cmd("ext/time64.h")],
    [#cmd("clib64.h")], [#cmd("ext/int64.h")],
    [#cmd("clibthrd.h")], [#cmd("mvs/thread.h")],
    [#cmd("clibenv.h")], [#cmd("mvs/env.h")],
    [#cmd("cliblock.h")], [#cmd("mvs/lock.h")],
    [#cmd("clibjes2.h")], [#cmd("mvs/jes2.h")],
    [#cmd("cliblist.h")], [#cmd("mvs/dslist.h")],
    [#cmd("cliblink.h")], [#cmd("mvs/link.h")],
    [#cmd("svc99.h")], [#cmd("mvs/dynalloc.h")],
    [#cmd("clibio.h")], [split: #cmd("stdio.h"), #cmd("mvs/dynalloc.h"),
      #cmd("mvs/pds.h"), #cmd("mvs/file.h")],
    [#cmd("clibstr.h")], [split: #cmd("string.h"), #cmd("strings.h"),
      #cmd("ext/strutil.h"), #cmd("unistd.h")],
    [#cmd("mvssupa.h")], [split: #cmd("mvs/clock.h"), #cmd("mvs/storage.h"),
      #cmd("mvs/dynalloc.h"), #cmd("mvs/idcams.h")],
    [#cmd("socket.h")], [split: #cmd("sys/socket.h"), #cmd("netinet/in.h"),
      #cmd("sys/select.h"), #cmd("arpa/inet.h"), #cmd("netdb.h"),
      #cmd("mvs/socket.h")],
    [#cmd("cvt.h"), #cmd("ihascvt.h"), #cmd("osdcb.h"), ...],
      [#cmd("ibm/mvs/...")],
    [#cmd("clibb64.h")], [removed: #cmd("base64.h") of crypto370],
  )
] <pg-migrate-headers-tab>

For a split header, include only the headers that declare the names the
source actually uses. The procedure below finds them.

== Migrating a Source File <pg-migrate-procedure>

#idx("migration", "procedure")
The libc370 source repository keeps three maps in its directory
#cmd("sdk/"), tab-separated text with one row per entry:

#deflist(width: 1.5in,
  [#cmd("headermap.tsv")], [one row per 1.x header: where it went. The
    target is a path under #cmd("include/") (the header moved), the same
    name (an ISO C header, unchanged), #cmd("split"), #cmd("internal") (it
    left the sysroot) or #cmd("removed").],
  [#cmd("names.tsv")], [one row per public name of 2.0: the header or
    headers that declare it.],
  [#cmd("removed.tsv")], [one row per 1.x name that no public header
    declares any more, with what to use instead.],
)

For each source file:

+ *Collect* the library headers the file includes and the identifiers it
  uses, leaving out comments and string literals.
+ *Rewrite each include* by its row in #cmd("headermap.tsv"). A moved
  header is replaced by its new name\; an unchanged ISO header stays\; a
  #cmd("split"), #cmd("internal") or #cmd("removed") header is dropped, and
  the next step supplies what the file needs from it.
+ *Resolve by name.* For every identifier the file uses that
  #cmd("names.tsv") lists, make sure the file includes one of its headers --
  the one it includes already, if any, otherwise the first one listed. This
  also catches names the file only saw through another header: the 1.x
  #cmd("socket.h") pulled in every socket header, the 2.0
  #cmd("<mvs/socket.h>") does not.
+ *Replace removed names* by their row in #cmd("removed.tsv")
  (@pg-migrate-removed).
+ *Keep the delimiters:* library headers are included as
  #cmd("<")...#cmd(">").

A header of the program's own that has the same base name as a library
header is not the library's: resolve includes against the program's own
tree first.

@pg-migrate-ex-fig shows the lines of a 1.x source that change, and the
migrated function.

#fig(caption: [A source before and after the migration])[
  #code(read("../ex/pg-migrate/before.txt"))
  #code(read("../ex/pg-migrate/runstep.c"), numbers: true)
] <pg-migrate-ex-fig>

== Names That Were Removed <pg-migrate-removed>

#idx("removed names")
Of the names that left the public headers, nearly all had no code behind
them or were internal to the library. The rows of #cmd("removed.tsv") say
which, in the column #cmd("now"):

#deflist(width: 1.6in,
  [#var("header") #var("name")], [use #var("name") from #var("header")
    instead.],
  [#cmd("crypto370") #var("header") #var("name")], [the name moved to
    crypto370.],
  [#cmd("internal")], [still in the library, but private. A program that
    uses it needs a decision, not a rewrite.],
  [#cmd("-")], [gone, with nothing in its place: declared but never
    implemented.],
)

The replacements a program is most likely to need:

#tab(caption: [Removed names and their replacements])[
  #table(columns: (1.4in, 1.6in, 1fr), align: left,
    [*1.x*], [*2.0*], [*Note*],
    [#cmd("bcopy()")], [#cmd("memmove()"), #cmd("<string.h>")], [*The first
      two arguments change places:* #cmd("bcopy(src, dst, n)") is
      #cmd("memmove(dst, src, n)").],
    [#cmd("stricmp()"), #cmd("strncmpi()")], [#cmd("strcasecmp()"),
      #cmd("strncasecmp()"), #cmd("<strings.h>")], [the same code under the
      POSIX names],
    [#cmd("__getcrt()"), #cmd("__getgrt()"), #cmd("__getwsa()")],
      [#cmd("__crtget()"), #cmd("__grtget()"), #cmd("__wsaget()")], [and
      likewise #cmd("__setcrt") to #cmd("__crtset"), #cmd("__rescrt") to
      #cmd("__crtres"), and so on],
    [#cmd("sha256_...()"), #cmd("blowfish_...()"), #cmd("base64_...()")],
      [crypto370], [same C names],
  )
] <pg-migrate-removed-tab>

== Interfaces That Changed Meaning <pg-migrate-meaning>

#idx("migration", "changed interfaces")
The maps place names. They cannot tell that a name kept its place and
changed what it means. These did -- find their uses and decide each one,
rather than rewriting them blindly.

#tab(caption: [Interfaces whose meaning changed in 2.0])[
  #table(columns: (1.1in, 1fr, 1fr), align: left,
    [*Name*], [*1.x*], [*2.0*],
    [#cmd("in_addr_t")], [#cmd("struct in_addr")], [#cmd("unsigned long"),
      the address itself. A cast to #cmd("in_addr_t *") for
      #cmd("inet_aton()") becomes #cmd("struct in_addr *").],
    [#cmd("inet_aton()")], [0 for an address, -1 for none\; second argument
      #cmd("in_addr_t *")], [1 for an address, 0 for none, as on BSD\;
      second argument #cmd("struct in_addr *")],
    [#cmd("__listpd()")], [when storage ran out, returned the members
      collected so far], [returns #cmd("NULL") with #cmd("errno")
      #cmd("ENOMEM"). A caller that reads #cmd("NULL") as "no members"
      reports an empty library. Better: move to #cmd("__walkpd()").],
    [#cmd("JESJOB"), #cmd("DSLIST")], [80 and 98 bytes], [96 and 104 bytes:
      new fields appended, every 1.x offset unchanged. The library allocates
      both, so a program only needs to be compiled again.],
  )
] <pg-migrate-meaning-tab>

Two more things met in the first programs migrated:

- *A private copy of a name that the library now has collides with it.*
  A program that brought its own #cmd("socklen_t"), #cmd("inet_addr()") or
  #cmd("inet_ntoa()") drops them and uses the library's. Note that
  #cmd("inet_ntoa()") returns #cmd("NULL") when the program has no run-time
  anchor, and shares one buffer between all tasks\; #cmd("inet_ntop()")
  into a buffer of your own has neither problem.
- *A library you publish* whose public header includes a libc370 header
  cannot be used by a program that is still on 1.x once it is built against
  2.0. Publish its 2.0 build as a prerelease until its users have moved:
  mbt offers a prerelease only to a version range that names one.

== New in 2.0 <pg-migrate-new>

Nothing here has to change for a program to build against 2.0. Each entry
is something a program may have worked around, and may now drop.

#tab(caption: [New interfaces in 2.0])[
  #table(columns: (1.9in, 1fr), align: left,
    [*New*], [*Replaces*],
    [#cmd("__walkpd()") in #cmd("<mvs/dslist.h>"): a PDS directory member
      by member through a callback, nothing allocated], [#cmd("__listpd()"),
      one allocation per member, which a large library can exhaust the region
      with],
    [#cmd("idcams_sysprint()") in #cmd("<mvs/idcams.h>"): every SYSPRINT
      line of IDCAMS with its message number], [reading the condition code
      of #cmd("idcams()"), which cannot tell "not found" from "refused"],
    [#cmd("inet_addr()"), #cmd("inet_pton()"), #cmd("inet_ntop()"),
      #cmd("inet_ntoa()") in #cmd("<arpa/inet.h>")], [#cmd("sscanf()") of
      the four parts, private copies],
    [#cmd("JESJOB.submit_time64"), #cmd("JESJOB.sysid") in
      #cmd("<mvs/jes2.h>")], [--],
    [#cmd("DSLIST.catnm") in #cmd("<mvs/dslist.h>"): the catalog in which
      #cmd("__listds()") found each entry], [--],
    [#cmd("fopen(")#var("dsn")#cmd(", \"w,unit=...,volser=...\")"): a new
      data set on the unit and volume named], [#cmd("__dsalcf()") with
      #cmd("UNIT=") and #cmd("VOLSER="), then #cmd("fopen()") of the DD],
  )
] <pg-migrate-new-tab>

== Verifying a Migrated Program <pg-migrate-verify>

- It builds against the 2.0 sysroot with #cmd("-Wall -Werror"). An implicit
  declaration means that step 3 of the procedure missed a name.
- Its generated assembler is the same as that of the 1.x build, source by
  source, with two exceptions: sources that differ only in the numbers of
  the compiler's labels (#cmd("@@F")#var("n"), #cmd("@@L")#var("n")),
  because a 1.x header carried a #cmd("static") function that the 2.0 one
  does not\; and sources that use one of the changed interfaces or a
  replaced name. Compile both sides with #cmd("-S") and compare. Any other
  difference is a missed include.

== Changes After 2.0.0 <pg-migrate-since>

What later 2.x releases ask of a program or a build:

#tab(caption: [Changes since 2.0.0])[
  #table(columns: (0.8in, 1fr, 1fr), align: left,
    [*Release*], [*Change*], [*What to do*],
    [2.1.0], [Needs cc370 1.1.0 or later. Every header stops with
      #cmd("#error") otherwise.], [Install a current cc370.],
    [2.1.0], [The compiler's helper routines, such as the 64-bit division,
      moved to cc370's #cmd("libcc370rt.a").], [A build that runs ld370
      itself adds #cmd("-lcc370rt").],
    [2.2.0], [#cmd("setbuf()") returns #cmd("void").], [Stop using its
      return value.],
    [after 2.2.0], [#cmd("PDPMAIN"), #cmd("PDP370"), #cmd("PDP380"),
      #cmd("PDP390") and #cmd("PDPORIG") are no longer shipped.],
      [Compile again with cc370 the C source of any assembler that copies
      #cmd("PDPMAIN"). Remove the old members from the sysroot's
      #cmd("macros") directory by hand: #cmd("make install") does not
      delete.],
  )
] <pg-migrate-since-tab>
