#!/usr/bin/env python3
"""names -- which public header declares which name, 1.x and 2.0 (#274).

sdk/headermap.tsv maps headers.  A consumer migration needs names as well: a
split header's declarations went to several targets, a name can have moved
into another header, and some are gone.  Three files, one question each:

    sdk/names-1.x.tsv   every name a public header declared in libc370 1.x,
                        with its header(s).  Frozen: taken once from v1.0.8.
    sdk/names.tsv       the same for include/ as it is now.  Generated.
    sdk/removed.tsv     every name of 1.x that no public header declares any
                        more, and what a consumer does instead.  Maintained
                        by hand, one row per name:

                            name  was(1.x headers)  now  note

                        "now" is one of
                            -                       gone, nothing replaces it
                            internal                still in libc370, but in a
                                                    private header under src/
                            <hdr> name              use that name from that
                                                    public header instead
                            crypto370 <hdr> name    the same, from crypto370

A name is what sdk/splithdr.py's scan finds in a header: functions, typedefs,
struct/union/enum tags, macros; not the include guard.  The scan is the same
for both sides, so a struct member it happens to count shows up on both and
cancels out.

check (run by sdk/headermap.py check, so in CI) fails when names.tsv is out
of date, when a name disappears from include/ without a row in removed.tsv,
when a row names something that is not gone, and when a row's replacement
does not exist: "internal" must be declared under src/, "<hdr> name" must be
in names.tsv under that header.

Usage:  python3 sdk/names.py render            # rewrite sdk/names.tsv
        python3 sdk/names.py check
        python3 sdk/names.py snapshot v1.0.8   # (once) rewrite names-1.x.tsv
"""
import os, re, sys, glob, subprocess, collections

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "sdk"))
import splithdr

NAMES = os.path.join(ROOT, "sdk", "names.tsv")
OLD = os.path.join(ROOT, "sdk", "names-1.x.tsv")
REMOVED = os.path.join(ROOT, "sdk", "removed.tsv")
HEAD = "# name\theader(s)"


def declared(text):
    text = text.replace("\r\n", "\n")
    m = re.match(r"\s*#ifndef[ \t]+(\w+)\s*\n#define[ \t]+\1", text)
    return splithdr.names(text) - ({m.group(1)} if m else set())


def scan(paths, base):
    """{name: {header, ...}} for the headers under base"""
    out = collections.defaultdict(set)
    for p in paths:
        for n in declared(open(p, "rb").read().decode("latin-1")):
            out[n].add(os.path.relpath(p, base))
    return out


def public():
    inc = os.path.join(ROOT, "include")
    return scan(glob.glob(os.path.join(inc, "**", "*.h"), recursive=True), inc)


def private():
    """names declared by headers under src/ (attic/ is outside it)"""
    paths = glob.glob(os.path.join(ROOT, "src", "**", "*.h"), recursive=True)
    return scan(paths, ROOT)


def dump(table, comment):
    lines = [comment, HEAD]
    lines += [f"{n}\t{' '.join(sorted(h))}" for n, h in sorted(table.items())]
    return "\n".join(lines) + "\n"


def load(path):
    out = {}
    for line in open(path, encoding="utf-8"):
        if line.startswith("#") or not line.strip():
            continue
        n, h = line.rstrip("\n").split("\t")
        out[n] = set(h.split())
    return out


def load_removed():
    rows = {}
    for i, line in enumerate(open(REMOVED, encoding="utf-8"), 1):
        if line.startswith("#") or not line.strip():
            continue
        cells = line.rstrip("\n").split("\t")
        if len(cells) != 4:
            sys.exit(f"{REMOVED}:{i}: want 4 tab-separated cells, got {len(cells)}")
        rows[cells[0]] = {"was": cells[1], "now": cells[2], "note": cells[3], "line": i}
    return rows


GENERATED = "# generated by sdk/names.py from include/ -- do not edit, run 'python3 sdk/names.py render'"


def cmd_render():
    open(NAMES, "w", encoding="utf-8").write(dump(public(), GENERATED))
    print(f"[names] {os.path.relpath(NAMES, ROOT)} rendered")
    return 0


def cmd_snapshot():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    ref = sys.argv[2]
    files = subprocess.run(["git", "-C", ROOT, "ls-tree", "-r", "--name-only", ref, "include/"],
                           capture_output=True, text=True, check=True).stdout.split()
    out = collections.defaultdict(set)
    for f in files:
        if f.endswith(".h"):
            t = subprocess.run(["git", "-C", ROOT, "show", f"{ref}:{f}"],
                               capture_output=True, check=True).stdout.decode("latin-1")
            for n in declared(t):
                out[n].add(f[len("include/"):])
    open(OLD, "w", encoding="utf-8").write(
        dump(out, f"# the public names of libc370 {ref}, frozen; taken by 'sdk/names.py snapshot {ref}'"))
    print(f"[names] {os.path.relpath(OLD, ROOT)}: {len(out)} names from {ref}")
    return 0


# Known answers for the scan, checked first: a scan that misses whole
# branches still "passes" everything below, since it misses them on both
# sides.  It did: ext/time64.h's API sits in the #else of an #if the scan
# took for dead, and gmtime64 was in neither list.
KNOWN = [("gmtime64", "ext/time64.h", True),     # #else of "#if defined(__LP64__)"
         ("memset",   "string.h",     True),     # #else of "#if 0"
         ("printf",   "stdio.h",      True),
         ("ENOMEM",   "errno.h",      True),
         ("ENOSYS",   "errno.h",      False),    # only inside "#if 0"
         ("__SIGHDL", "signal.h",     True)]     # a function-pointer typedef


def cmd_check():
    bad = 0
    now = public()
    for name, hdr, want in KNOWN:
        if (hdr in now.get(name, ())) != want:
            print(f"[names] scan: {name} {'missing from' if want else 'wrongly found in'} {hdr}")
            bad += 1
    if open(NAMES, encoding="utf-8").read() != dump(now, GENERATED):
        print("[names] sdk/names.tsv is out of date: run 'python3 sdk/names.py render'")
        bad += 1
    old, rows, priv = load(OLD), load_removed(), private()
    gone = set(old) - set(now)
    missing = sorted(gone - set(rows))
    if missing:
        print(f"[names] gone from include/ but not in sdk/removed.tsv: {', '.join(missing)}")
        bad += 1
    stale = sorted(set(rows) - gone)
    if stale:
        print(f"[names] in sdk/removed.tsv but not gone: {', '.join(stale)}")
        bad += 1
    for n, r in sorted(rows.items()):
        where = f"sdk/removed.tsv:{r['line']}: {n}"
        now_ = r["now"].split()
        if r["was"] != " ".join(sorted(old.get(n, ()))) and n in old:
            print(f"[names] {where}: 'was' should read '{' '.join(sorted(old[n]))}'")
            bad += 1
        if now_ == ["-"]:
            continue
        if now_ == ["internal"]:
            if n not in priv:
                print(f"[names] {where}: marked internal, but no header under src/ declares it")
                bad += 1
            continue
        if now_ and now_[0] == "crypto370" and len(now_) == 3:
            continue
        if len(now_) == 2 and now_[0].startswith("<") and now_[0].endswith(">"):
            hdr, name = now_[0][1:-1], now_[1]
            if hdr not in now.get(name, ()):
                print(f"[names] {where}: replacement {name} is not declared in <{hdr}>")
                bad += 1
            continue
        print(f"[names] {where}: 'now' must be '-', 'internal', '<hdr> name' or 'crypto370 <hdr> name'")
        bad += 1
    kinds = collections.Counter(("-" if r["now"] == "-" else r["now"].split()[0]
                                 if r["now"].split()[0] in ("internal", "crypto370") else "replaced")
                                for r in rows.values())
    print(f"[names] {len(old)} names in 1.x, {len(now)} now; {len(gone)} gone: "
          + ", ".join(f"{k} {v}" for k, v in sorted(kinds.items()))
          + (f"; {bad} problem(s)" if bad else "; consistent"))
    return 1 if bad else 0


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "check"
    fn = {"render": cmd_render, "check": cmd_check, "snapshot": cmd_snapshot}.get(cmd)
    if not fn:
        sys.exit(__doc__)
    sys.exit(fn())
